version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db

  db:
    image: 5.7.16
    restart: always
    environment:
      MYSQL_DATABASE: 'sandeo'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_data:
